# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_new',
                'doc_host': 'https://barz-christian.github.io',
                'git_url': 'https://github.com/barz-christian/nbdev_new',
                'lib_path': 'nbdev_new'},
  'syms': {'nbdev_new.core': {'nbdev_new.core.foo': ('core.html#foo', 'nbdev_new/core.py')}}}
